defmodule AshAgent.Domain do
  @moduledoc """
  The AshAgent domain extension.

  This extension allows you to configure agent behavior at the domain level,
  providing global configuration for all agent resources in your domain.

  ## Usage

  Add the extension to your domain:

  ```elixir
  defmodule MyApp.Domain do
    use Ash.Domain,
      extensions: [AshAgent.Domain]

    agent do
      # Domain-level agent configuration
    end

    resources do
      resource MyApp.MyAgent
    end
  end
  ```

  ## DSL Documentation

  DSL documentation will be auto-generated by Spark.
  """

  @agent %Spark.Dsl.Section{
    name: :agent,
    describe: """
    Domain-level configuration for agent behavior.

    This section allows you to configure default behavior for all agent resources
    in this domain.
    """,
    examples: [
      """
      agent do
        # Domain-level agent configuration
      end
      """
    ],
    schema: []
  }

  use Spark.Dsl.Extension,
    sections: [@agent],
    transformers: []
end
