defmodule AshAgent.Domain do
  @moduledoc """
  The AshAgent domain extension.

  This extension allows you to configure agent behavior at the domain level,
  providing global configuration for all agent resources in your domain.

  ## Usage

  Add the extension to your domain:

  ```elixir
  defmodule MyApp.Domain do
    use Ash.Domain,
      extensions: [AshAgent.Domain]

    agent do
      # Domain-level agent configuration
    end

    resources do
      resource MyApp.MyAgent
    end
  end
  ```

  ## Registering Agent Templates

  You can register agent templates from AshAgentMarketplace or your own templates:

  ```elixir
  defmodule MyApp.Agents do
    use Ash.Domain, extensions: [AshAgent.Domain]

    agents do
      agent AshAgentMarketplace.Agents.TitleGenerator,
        client: "openai:gpt-4o"
    end
  end
  ```

  ## DSL Documentation

  DSL documentation will be auto-generated by Spark.
  """

  @agent_entity %Spark.Dsl.Entity{
    name: :agent,
    describe: "Registers an agent template with client configuration",
    examples: [
      "agent MyApp.Templates.Summarizer, client: \"openai:gpt-4o\"",
      "agent AshAgentMarketplace.Agents.TitleGenerator, client: \"anthropic:claude-3-5-sonnet\", as: :title_gen"
    ],
    target: AshAgent.Domain.AgentConfig,
    args: [:template],
    schema: [
      template: [
        type: :atom,
        required: true,
        doc: "The agent template module to use"
      ],
      client: [
        type: {:custom, AshAgent.DSL, :validate_client_config, []},
        required: true,
        doc: "The LLM client string (e.g., \"openai:gpt-4o\")"
      ],
      provider: [
        type: :atom,
        doc: "The provider implementation (defaults to :req_llm)"
      ],
      as: [
        type: :atom,
        doc: "Override the generated module name"
      ],
      extensions: [
        type: {:list, :any},
        doc: "Additional Ash extensions to include"
      ]
    ]
  }

  @agents %Spark.Dsl.Section{
    name: :agents,
    describe: "Register agent templates with client configuration",
    entities: [@agent_entity]
  }

  @agent %Spark.Dsl.Section{
    name: :agent,
    describe: """
    Domain-level configuration for agent behavior.

    This section allows you to configure default behavior for all agent resources
    in this domain.
    """,
    examples: [
      """
      agent do
        auto_define_interfaces? true
      end
      """
    ],
    schema: [
      auto_define_interfaces?: [
        type: :boolean,
        default: true,
        doc: """
        When true, automatically generates named code interface functions
        (`call_<resource_name>` and `stream_<resource_name>`) for all agent
        resources in this domain.

        The generated interfaces use the input arguments defined in each
        agent's `input` section as function arguments.
        """
      ]
    ]
  }

  use Spark.Dsl.Extension,
    sections: [@agent, @agents],
    transformers: [
      AshAgent.Domain.Transformers.GenerateAgents,
      AshAgent.Transformers.AddDomainInterfaces
    ]
end
