defmodule AshAgent.Resource do
  @moduledoc """
  The AshAgent resource extension.

  This extension allows you to add agent capabilities to your Ash resources,
  enabling them to interact with LLMs and perform agent-based operations.

  ## Usage

  Add the extension to your resource:

  ```elixir
  defmodule MyApp.MyAgent do
    use Ash.Resource,
      domain: MyApp.Domain,
      extensions: [AshAgent.Resource]

    agent do
      # Agent configuration will go here
    end
  end
  ```

  ## DSL Documentation

  DSL documentation will be auto-generated by Spark.
  """

  @agent %Spark.Dsl.Section{
    name: :agent,
    describe: """
    Configuration for agent behavior and capabilities.
    """,
    examples: [
      """
      agent do
        # Agent configuration
      end
      """
    ],
    schema: [
      enabled: [
        type: :boolean,
        default: true,
        doc: "Whether agent functionality is enabled for this resource."
      ]
    ]
  }

  use Spark.Dsl.Extension,
    sections: [@agent],
    transformers: []
end
